Repository atlp-rwanda/phantom-be-codebandits, pull requests merged in 2022-04, with the labels that each got.

#5 #CP-17 ch: setup-docker-postgress-database
  .dockerignore
  .env.sample
  .github/workflows/dev_deploy.yml
  .github/workflows/main.yml
  .github/workflows/pro_deploy.yml
  .gitignore
  Dockerfile
  README.md
  docker-compose.yml
  jsconfig.json
  locales/en.json
  locales/fr.json
  locales/kn.json
  package-lock.json
  package.json
  public/swagger.css
  src/app.js
  src/configs/reqLogger.js
  src/configs/swagger.js
  src/controllers/user.js
  src/data-source.js
  src/docs/userRouter.docs.js
  src/middlewares/idRequired.js
  src/models/user.js
  src/routes/apiRouter.js
  src/routes/tests/userRouter.test.js
  src/routes/userRouter.js
  src/seeder/user.seed.js
  src/tests/app.test.js
  src/utils/asyncHandler.js
Labels: Need Reviews

#6 #CP-18 chore: heroku postgres provisioning and configuration
  Procfile
  src/app.js
  src/data-source.js
Labels: Need Reviews

#7 #CP-8 feat: Sign in to phantom
  .env.sample
  .eslintrc.json
  .github/workflows/dev_deploy.yml
  .github/workflows/main.yml
  .github/workflows/pro_deploy.yml
  .husky/pre-commit
  locales/en.json
  locales/fr.json
  locales/kn.json
  package-lock.json
  package.json
  src/app.js
  src/controllers/auth.controller.js
  src/controllers/refreshToken.controller.js
  src/controllers/services/saveUser.js
  src/controllers/tests/auth.test.js
  src/controllers/tests/refreshToken.test.js
  src/controllers/user.js
  src/data-source.js
  src/docs/loginRouter.docs.js
  src/middlewares/authJwt.js
  src/middlewares/validations/auth.validation.js
  src/middlewares/verifyAuthValidation.js
  src/models/refreshToken.js
  src/models/user.js
  src/routes/accountsRouter.js
  src/routes/apiRouter.js
  src/routes/loginRouter.js
  src/routes/tests/userRouter.test.js
Labels: Need Reviews

#9 #CP-9 feat: roles and permissions
  .husky/pre-commit
  locales/en.json
  locales/fr.json
  locales/kn.json
  ormconfig.js
  package-lock.json
  package.json
  src/app.js
  src/configs/ac.js
  src/configs/grants.js
  src/controllers/auth.controller.js
  src/controllers/tests/auth.test.js
  src/controllers/tests/refreshToken.test.js
  src/controllers/user.js
  src/middlewares/CheckPermission.js
  src/middlewares/VerifyJWT.js
  src/middlewares/authJwt.js
  src/models/Permission.js
  src/models/Role.js
  src/rolesApp/controller.js
  src/rolesApp/validation.js
  src/routes/apiRouter.js
  src/routes/companiesRouter.js
  src/routes/driverRouter.js
  src/routes/operatorRoutes.js
  src/routes/tests/rolesTest.test.js
  src/routes/tests/userRouter.test.js
  src/routes/userRouter.js
  src/utils/errorLogger.js
Labels: Need Reviews

#11 #CP-21 feat: Logout from account
  locales/en.json
  locales/fr.json
  locales/kn.json
  src/controllers/auth.controller.js
  src/controllers/logout.controller.js
  src/controllers/refreshToken.controller.js
  src/controllers/tests/auth.test.js
  src/controllers/tests/logout.test.js
  src/docs/loginRouter.docs.js
  src/docs/logoutRouter.docs.js
  src/docs/refreshRouter.docs.js
  src/routes/accountsRouter.js
  src/routes/logoutRouter.js
  src/utils/clearCookie.js
Labels: Approved (pending merge)

#10 #CP-22 feat: reset password
  .husky/pre-commit
  Dockerfile
  locales/en.json
  locales/fr.json
  locales/kn.json
  package-lock.json
  package.json
  src/app.js
  src/controllers/tests/auth.test.js
  src/data-source.js
  src/docs/loginRouter.docs.js
  src/models/refreshToken.js
  src/routes/accountsRouter.js
  src/routes/loginRouter.js
  src/userApp/controllers.js
  src/userApp/docs.js
  src/userApp/emailMessage.js
  src/userApp/emailValidation.js
  src/userApp/models.js
  src/userApp/routes.js
  src/userApp/tests/controllers.test.js
  src/userApp/utils.js
  src/userApp/validatePassword.js
  src/utils/errorLogger.js
  src/utils/validate.js
Labels: Approved (pending merge)

#18 #CP-22 bug: Fix status code for request forbidden
  .github/pull_request_template.md
  .gitmessage.txt
  README.md
  locales/en.json
  locales/fr.json
  locales/kn.json
  src/configs/tests/dummyData.js
  src/driverApp/tests/driver.test.js
  src/middlewares/CheckPermission.js
  src/middlewares/authJwt.js
  src/models/user.js
  src/operatorApp/tests/operator.test.js
  src/routes/tests/rolesTest.test.js
  src/userApp/tests/controllers.test.js
Labels: bug, Approved (pending merge)

#17 #CP-11 feat: CRUD operations for buses
  locales/en.json
  locales/fr.json
  locales/kn.json
  src/busesApp/controllers.js
  src/busesApp/docs.js
  src/busesApp/models.js
  src/busesApp/router.js
  src/busesApp/services.js
  src/busesApp/tests/buses.test.js
  src/busesApp/updateValidation.js
  src/busesApp/validations.js
  src/configs/tests/dummyData.js
  src/controllers/services/saveUser.js
  src/controllers/tests/auth.test.js
  src/controllers/user.js
  src/data-source.js
  src/routes/apiRouter.js
  src/services/saveService.js
Labels: Approved (pending merge)

#15 #CP-7 feat: crud operations for routes
  locales/en.json
  locales/fr.json
  locales/kn.json
  package-lock.json
  package.json
  src/configs/tests/dummyData.js
  src/controllers/handleResponse.js
  src/data-source.js
  src/docs/logoutRouter.docs.js
  src/docs/refreshRouter.docs.js
  src/models/base.js
  src/routeApp/controllers.js
  src/routeApp/docs.js
  src/routeApp/models.js
  src/routeApp/routes.js
  src/routeApp/services.js
  src/routeApp/tests/controllers.test.js
  src/routeApp/utils.js
  src/routeApp/validations.js
  src/routes/apiRouter.js
Labels: Need Reviews

#16 #CP-13 feat: assign bus to routes
  .github/pull_request_template.md
  locales/en.json
  src/app.js
  src/busesApp/controllers.js
  src/busesApp/docs.js
  src/busesApp/models.js
  src/busesApp/router.js
  src/busesApp/services.js
  src/busesApp/tests/buses.test.js
  src/busesApp/validations.js
  src/bustoRouteApp/controllers.js
  src/bustoRouteApp/docs.js
  src/bustoRouteApp/routes.js
  src/bustoRouteApp/tests/busToRoute.test.js
  src/bustoRouteApp/validation.js
  src/configs/grants.js
  src/configs/tests/dummyData.js
  src/controllers/refreshToken.controller.js
  src/controllers/tests/refreshToken.test.js
  src/data-source.js
  src/driverApp/tests/driver.test.js
  src/middlewares/CheckPermission.js
  src/middlewares/VerifyJWT.js
  src/models/Permission.js
  src/models/Role.js
  src/routeApp/controllers.js
  src/routeApp/models.js
  src/routeApp/tests/controllers.test.js
  src/routes/apiRouter.js
Labels: Approved (pending merge)

#19 #CP-12 feat: assign drivers to buses
  locales/en.json
  locales/fr.json
  locales/kn.json
  src/busesApp/controllers.js
  src/busesApp/docs.js
  src/busesApp/models.js
  src/busesApp/router.js
  src/busesApp/tests/buses.test.js
  src/configs/swagger.js
  src/configs/winston.js
  src/driverApp/controllers.js
  src/driverApp/docs.js
  src/driverApp/models.js
  src/driverApp/router.js
  src/operatorApp/docs.js
  src/routeApp/docs.js
  src/services/baseServices.js
  src/templates/assignEmail.js
  src/userApp/controllers.js
  src/utils/sendAssignEmail.js
Labels: Need Reviews

#20 #CP-23 Fix CORS error in credential request
  src/app.js
  src/configs/cors.js
  src/controllers/auth.controller.js
  src/controllers/refreshToken.controller.js
  src/controllers/tests/refreshToken.test.js
Labels: Need Reviews

#22 #CP-31 bug: backend quick fixes
  package-lock.json
  src/busesApp/services.js
  src/busesApp/updateValidation.js
  src/controllers/refreshToken.controller.js
  src/controllers/tests/refreshToken.test.js
  src/driverApp/models.js
  src/driverApp/tests/driver.test.js
Labels: Approved (pending merge)
